// Port of lib/asciidoctor_revealjs/stylesheet.rb
//
// The CSS generated by the Asciidoctor reveal.js converter to further integrate
// AsciiDoc's existing semantic with reveal.js. It is embedded verbatim into the
// document <head> by the converter.

import { readFileSync } from 'node:fs'

export const COMPATIBILITY = readFileSync(
  new URL('../../data/compatibility.css', import.meta.url),
  'utf8'
)
