= Specific Roles
:navtitle: Roles

Roles are usually applied with the following syntax where the `important-text` CSS class would be applied to the slide title in the generated HTML:

[source, asciidoc]
....
[.important-text]
== Slide Title

* Some
* Information
....

Or

[source, asciidoc]
....
[role="important-text"]
== Slide Title

* Some
* Information
....

See xref:asciidoc:attributes:roles.adoc[Asciidoctor's documentation] for more details.

.Image-specific note
In addition to the xref:asciidoc:macros:image-position.adoc#positioning-attributes[existing attributes] used to position images, roles can be used as well.
However, the shorthand dot (`.`) syntax doesn't work inside the image macro arguments: use the `role` attribute instead.
See xref:attachment$images.adoc[images.adoc] for examples.

Here is a list of supported roles:

right:: Will apply a `float: right` style to the affected block
text-left:: Left-aligns the affected block's text
text-right:: Right-aligns the affected block's text
text-center:: Center-aligns the affected block's text
text-justify:: Justifies the affected block's text
small:: On a paragraph, wraps its content in `<small>` instead of `<p>`
