= reveal.js Plugins
:navtitle: Plugins

== Default plugins

By default, generated presentations will have the following reveal.js plugins enabled:

* plugin/zoom/zoom.js
* plugin/notes/notes.js

All these plugins are part of the reveal.js built-in Plugins.

To enable or disable a built-in plugin, it is possible to set the `revealjs_plugin_[plugin name]` attribute to `enable` or `disable`.

For example, to disable all the default plugins set the following document attributes:

----
:revealjs_plugin_zoom: disabled
:revealjs_plugin_notes: disabled
----

For the reveal.js built-in Plugins which are not loaded by default, you can enable
them explicitly:

----
:revealjs_plugin_markdown: enabled
:revealjs_plugin_search: enabled
:revealjs_plugin_math: enabled
:revealjs_plugin_highlight: enabled 
----

== Additional plugins

=== Introducton

Additional reveal.js plugins can be installed and activated using asciidoctor-revealjs docinfo mechanism.
You can check the detail of this mechanism here: https://docs.asciidoctor.org/asciidoctor/latest/docinfo/

In revealjs-asciidoctor, adoc file will be converted to HTML file, and from HTML point of view: 
. To install and activate additional plugins, you may need to set reveal initializating object properties,  which you can directly use `revealConfig` in your docinfo file. 
. You can push loaded plugins to `revealConfig.plugins`, so that asciidoctor-revealjs will register them for you.

=== Procedure

. Extract the plugin files in a directory
. Create docinfo file and enable it in your adoc file

Looking at the example provided in the repository will provide guidance: link:{url-project-examples}/revealjs-plugins.adoc[AsciiDoc source], link:{url-project-examples}/docinfo-footer.html[Plugin Loader].

Provide that you put additional plugins in reveal.js/plugin, 
and your slide adoc out put html file is slibing of reveal.js folder.
you can load additional plugins as below.

. In your adoc file, add `:docinfo: shared` and `:docinfodir: .`.
Looking at the example provided in the repository will provide guidance: link:{url-project-examples}/revealjs-plugins.adoc[AsciiDoc source]
. create docinfo-footer.html at the same folder as you adoc file, the code is listed below, which will load 
chalkboard and menu plugins: +
[source,html]
----
<!--chalkboard-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css">
<link rel="stylesheet" href="./reveal.js/plugin/chalkboard/style.css">
<script type="text/javascript" src="./reveal.js/plugin/chalkboard/plugin.js"></script>
<script type="text/javascript">
  revealConfig.plugins.push(RevealChalkboard);
  revealConfig.chalkboard={ // font-awesome.min.css must be available
    src: "chalkboard/chalkboard.json",
    storage: "chalkboard-demo",
    toggleChalkboardButton: { left: "80px" },
    toggleNotesButton: { left: "130px" },
    colorButtons: 5
  }
</script>

<!--menu-->
<script type="text/javascript" src="./reveal.js/plugin/menu/menu.js"></script>
<script type="text/javascript">
    revealConfig.plugins.push(RevealMenu);
</script>
----


Looking at the example provided in the repository will provide guidance: link:{url-project-examples}/docinfo-footer.html}[Plugin Loader].