= reveal.js Plugins
:navtitle: Plugins

== Default plugins

By default, generated presentations will have the following built-in reveal.js plugins enabled:

* `dist/plugin/zoom.js`
* `dist/plugin/notes.js`

All these plugins are part of the reveal.js distribution.

To enable or disable a built-in plugin, it is possible to set the `+revealjs_plugin_{plugin name}+` attribute to `enabled` or `disabled`.

For example, to disable all the default plugins set the following document attributes:

----
:revealjs_plugin_zoom: disabled
:revealjs_plugin_notes: disabled
----

== Additional plugins

Additional reveal.js plugins can be installed and activated using xref:asciidoc:docinfo:index.adoc[docinfo files].

. Extract the plugin files into a directory
. Load each plugin's script and stylesheet from a head docinfo file
. Configure and initialize the plugins from a footer docinfo file
. Add a `:docinfo:` attribute to enable docinfo

Let's take an example where we want to use the https://github.com/rajgoel/reveal.js-plugins/tree/master/chalkboard[chalkboard plugin] and the https://github.com/rajgoel/reveal.js-plugins/tree/master/customcontrols[customcontrols plugin].
First, download the plugins from GitHub and extract the `chalkboard` and `customcontrols` directories into a `reveal.js-plugins` folder:

[source,console]
----
$ tree reveal.js-plugins -L 2
----

....
reveal.js-plugins
├── chalkboard
│   ├── img
│   ├── plugin.js
│   ├── README.md
│   └── style.css
└── customcontrols
    ├── plugin.js
    ├── README.md
    └── style.css

4 directories, 6 files
....

Loading a plugin happens in two steps: load its assets, then initialize it.

First, load each plugin's script and stylesheet from a head docinfo file named `<docname>-docinfo-revealjs.html`, where `<docname>` is the name of your AsciiDoc file (here, `presentation.adoc`).
The customcontrols plugin renders its buttons with https://fontawesome.com[Font Awesome^] icons, so load Font Awesome as well:

.presentation-docinfo-revealjs.html
[source,html]
----
<script src="Font-Awesome/js/all.min.js"></script> <!--.-->
<link rel="stylesheet" href="Font-Awesome/css/all.min.css">
<script src="reveal.js-plugins/customcontrols/plugin.js"></script> <!--.-->
<link rel="stylesheet" href="reveal.js-plugins/customcontrols/style.css">
<script src="reveal.js-plugins/chalkboard/plugin.js"></script> <!--.-->
<link rel="stylesheet" href="reveal.js-plugins/chalkboard/style.css">
----
<.> Load Font Awesome, used by the customcontrols icons
<.> Load the customcontrols plugin and its stylesheet
<.> Load the chalkboard plugin and its stylesheet

Then, configure and initialize the plugins from a footer docinfo file named `<docname>-docinfo-footer.html`.
Each modern reveal.js plugin exposes an `init(Reveal)` function that you call once reveal.js is ready:

.presentation-docinfo-footer.html
[source,html]
----
<script>
  Reveal.configure({
    customcontrols: {
      controls: [
        { icon: '<i class="fa fa-pen-square"></i>',
          title: 'Toggle chalkboard (B)',
          action: 'RevealChalkboard.toggleChalkboard();' },
        { icon: '<i class="fa fa-pen"></i>',
          title: 'Toggle notes canvas (C)',
          action: 'RevealChalkboard.toggleNotesCanvas();' }
      ]
    }
  }) // <.>
  RevealChalkboard.init(Reveal) // <.>
  RevealCustomControls.init(Reveal) // <.>
</script>
----
<.> Configure the customcontrols to toggle the chalkboard and the notes canvas
<.> Initialize the chalkboard plugin
<.> Initialize the customcontrols plugin

Finally, enable docinfo in your presentation so that both files are picked up:

.presentation.adoc
[source,adoc]
----
= Third-party Plugins
:docinfo: private // <.>

// ...
----
<.> Enable private docinfo so the `presentation-docinfo-revealjs.html` and `presentation-docinfo-footer.html` files are included

TIP: A complete, working example is available in xref:attachment$revealjs-plugins.adoc[revealjs-plugins.adoc] together with its xref:attachment$revealjs-plugins-docinfo-revealjs.html[head] and xref:attachment$revealjs-plugins-docinfo-footer.html[footer] docinfo files.

[IMPORTANT]
====
By default, docinfo files are searched for in the same folder as the document file.
If you want to keep them anywhere else, set the docinfodir attribute to their location.

Please read xref:asciidoc:docinfo:index.adoc#resolving[] if you want to learn more.
====

Read https://revealjs.com/plugins/[the relevant reveal.js documentation] to understand more about reveal.js plugins.
A {url-revealjs-gh}/wiki/Plugins,-Tools-and-Hardware[list of existing reveal.js plugins] is also maintained upstream.

