== reveal.js Backend for Asciidoctor

The https://github.com/asciidoctor/asciidoctor-reveal.js[reveal.js backend] is a slim template which transforms an AsciiDoc document to HTML5 slides animated by http://lab.hakim.se/reveal-js/[reveal.js].

//image:https://travis-ci.org/asciidoctor/asciidoctor-reveal.js.svg?branch=master[Build Status,link=https://travis-ci.org/asciidoctor/asciidoctor-reveal.js]

== Usage Instructions

. Ensure Asciidoctor, Slim and their dependencies are installed:

  $ gem install asciidoctor tilt thread_safe
    gem install slim --version 2.1.0
+
WARNING: We recommend using Slim 2.1.0 until https://github.com/asciidoctor/asciidoctor-reveal.js/issues/8[issue #8] is resolved.

. Clone `asciidoctor/asciidoctor-reveal.js` to get templates for rendering presentation HTML:

  $ git clone git://github.com/asciidoctor/asciidoctor-reveal.js.git

. Edit `CONTENT_FILE` ( *.adoc or *.ad or ...):

  ** Slides & content per slide
  ** (Optional) Set presentation options at top of `CONTENT_FILE`.
     The options available & their values will depend on presentation library (some examples below).

  :${Attribute}: ${Value}

. Generate HTML from the Asciidoctor templates

  .. Command Line:

  $ asciidoctor -T templates/slim CONTENT_FILE

  .. Build Script: use Ruby, JavaScript, Gradle, or your favorite build tool/script with presentation options

. Copy or clone presentation library (to output destination/branch)

  $ git clone git://github.com/hakimel/reveal.js.git

TIP: If you are using https://pages.github.com/[GitHub Pages], plan ahead by keeping your source files on `master` branch and all output files on the `gh-pages` branch.

== Source Examples

// FIXME: incomplete

Let's see some examples of `revealjs` backend features:

----
= Title Slide

== Slide One

* Foo
* Bar
* World

== Slide Two

Hello World - Good Bye Cruel World

[NOTE.speaker]
--
Actually things aren't that bad
--
----

In previous snippet we are creating a slide titled Slide One with bullets and another one titled Slide Two with centered text (reveal.js' default behavior) with https://github.com/hakimel/reveal.js#speaker-notes[speaker notes].

----
[data-background="yellow"]
== Slide Three

Is very yellow
----

Slide Three applies the attribute http://lab.hakim.se/reveal-js/#/14[data-background] to the `reveal.js` <section> tag.
Anything accepted by CSS color formats works.
Here is the https://github.com/hakimel/reveal.js#slide-backgrounds[upstream documentation].

----
== Slide Four

[%step]
* this
* is
* revealed
* gradually

----

Slide Four has bullets that are revealed one after the other.
This is what `reveal.js` calls http://lab.hakim.se/reveal-js/#/fragments[fragments].
Applying the step option or role on a list (`[%step]` or `[.step]`) will do the trick.
Here is https://github.com/hakimel/reveal.js#fragments[upstream documentation] on the topic.
Note that only `fade-in` is supported for lists at the moment.

[listing]
....
== Slide Five

Uses highlighted code

----
print "Hello World"
----
....

`revealjs` uses https://highlightjs.org/[highlight.js] to do its syntax highlighting by default.
By default `[source]` blocks and blocks delimited by `----` will be highlighted.
An explicit `[listing]` block will not be highlighted.
`highlight.js` does language auto-detection but using the `language="..."` attribute will hint the highlighter.
For example this will highlight this source code as Perl:

[listing]
....
== Slide Five

[source, language="perl"]
----
print "$0: hello world\n"
----
....

[NOTE]
Currently `revealjs` uses a rather old version of https://highlightjs.org/[highlight.js] that does not handle callouts correctly.
To fix this download a current version of https://highlightjs.org/[highlight.js] and copy it to `reveal.js/plugin/highlight/highlight.js`.

Alternatively you can use http://coderay.rubychan.de[Coderay] or http://pygments.org[Pygments] as the highlighter.
These handle callouts correctly.

To use http://coderay.rubychan.de[Coderay]:

----
= Title slide
:source-highlighter: coderay
----

To use http://pygments.org[Pygments]:

----
= Title slide
:source-highlighter: pygments
----


[listing]
....
== Slide Six

Top slide

=== Slide Six.One

This is a vertical subslide
....

Slide Six uses the vertical slide feature of `reveal.js`.
Slide Six.One will be rendered vertically below Slide Six.
Here is https://github.com/hakimel/reveal.js#markup[upstream documentation] on that topic.

NOTE: The `reveal.js` backend only supports level 1 (`==`) and level 2 (`===`) sections. Level 3 sections are not supported and will not render correctly.

== reveal.js Options

There are some attributes that can be set at the top of the document which they are specific of +revealjs+ backend.

[NOTE]
--
Default settings are based on `reveal.js` default settings.
--

[options="header",cols="1m,1,2"]
|===
|Attribute    |Value(s)     |Description

|:revealjs_theme:
|*default*, beige, sky, night, serif, simple, solarized
|Chooses one of reveal.js' https://github.com/hakimel/reveal.js#theming[built-in themes].

|:revealjs_customtheme:
|<file\|URL>
| Overrides CSS with given file or URL. Default is disabled.

|:revealjsdir:
|<file\|URL>
| Overrides reveal.js directory. Example : ../reveal.js

|:revealjs_controls:
|*true*, false
|Display controls in the bottom right corner.

|:revealjs_progress:
|*true*, false
|Display a presentation progress bar.

|:revealjs_slideNumber:
|true, *false*
|Display the page number of the current slide.

|:revealjs_history:
|true, *false*
|Push each slide change to the browser history.

|:revealjs_keyboard:
|*true*, false
|Enable keyboard shortcuts for navigation.

|:revealjs_overview:
|*true*, false
|Enable the slide overview mode.

|:revealjs_touch:
|*true*, false
|Enables touch navigation on devices with touch input.

|:revealjs_center:
|*true*, false
|Vertical centering of slides.

|:revealjs_loop:
|true, *false*
|Loop the presentation.

|:revealjs_rtl:
|true, *false*
|Change the presentation direction to be RTL.

|:revealjs_fragments:
|*true*, false
|Turns fragments on and off globally.

|:revealjs_embedded:
|true, *false*
|Flags if the presentation is running in an embedded mode,
i.e. contained within a limited portion of the screen.

|:revealjs_autoSlide:
|<integer>
| Delay in milliseconds between automatically proceeding to the
next slide. +
Disabled when set to *0* (the default). +
This value can be overwritten by using a `data-autoslide` attribute on your slides.

|:revealjs_autoSlideStoppable:
|*true*, false
|Stop auto-sliding after user input.

|:revealjs_mouseWheel:
|true, *false*
|Enable slide navigation via mouse wheel.

|:revealjs_hideAddressBar:
|*true*, false
|Hides the address bar on mobile devices.

|:revealjs_previewLinks:
|true, *false*
|Opens links in an iframe preview overlay.

|:revealjs_transition:
|*default*, cube, page, concave, zoom, linear, fade, none
|Transition style.

|:revealjs_transitionSpeed:
|*default*, fast, slow
|Transition speed.

|:revealjs_backgroundTransition:
|*default*, none, slide, concave, convex, zoom
| Transition style for full page slide backgrounds.

|:revealjs_viewDistance:
|<integer>
|Number of slides away from the current that are visible. Default: 3

|:revealjs_parallaxBackgroundImage:
|<file\|URL>
|Parallax background image. Defaults to none

|:revealjs_parallaxBackgroundSize:
|<CSS size syntax>
|Parallax background size (accepts any CSS syntax). Defaults to none

|===

If you want to build a custom theme or customize an existing one you should look at the https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/asciidoc-to-pdf-example/pom.xml[reveal.js documentation] and use `revealjs_theme` AsciiDoc attribute to activate it.
