= Hacking

Short instructions that aim to help potential contributors.

== Getting Started

* Set up the Asciidoctor reveal.js plugin in xref:ruby-localversion[development mode]
* Modify the converter, written in plain Ruby, in `lib/asciidoctor_revealjs/converter.rb`

There is no build step: each AsciiDoc node is converted by a matching `convert_<node>` method.

* Render slides with your changes using:

 $ bundle exec asciidoctor-revealjs <source.adoc>

The next section will provide further help on how to use `print` statements or a debugger to assist development.


== Inspect the converter

To understand what you have access to while converting a node you can inject some Ruby.
Each `convert_<node>` method runs in the context of the node being converted (`self` is the node), so you can call node methods and inspect them directly.
Two complementary approaches can be used to explore the context offered by Asciidoctor:

* logging on the command line via print-like statements
* jump into the context through an interactive debugger

=== Print debugging information

For example to see which attributes are available, you can print them by adding these lines inside the relevant `convert_<node>` method:

----
puts @document.attributes.inspect
puts @attributes.inspect
puts @document.methods
----

Other generally useful Ruby specific introspection:

----
puts instance_variables
puts local_variables
----

One might find `pp` to produce better output (and in some cases not):

----
require 'pp'
pp @document.attributes
----

=== Interactively debug the converter

Pry is a powerful debugger for Ruby that features tab-completion.
It is very useful to discover a complex object hierarchy like what Asciidoctor offers.

==== Initial Setup

 $ bundle --path=.bundle/gems --binstubs=.bundle/.bin

==== Usage

In order to be dropped into the debugger at a specific point, add the following two lines inside the relevant `convert_<node>` method:

----
require 'pry'
binding.pry
----

Then run `asciidoctor-revealjs` from the command-line to generate your document and you'll be dropped in the debugger:

----
$ bundle exec asciidoctor-revealjs examples/video.adoc

From: lib/asciidoctor_revealjs/converter.rb @ line ... :

[1] pry(#<Asciidoctor::Section>)>
----

Then using commands like the following allows you to explore interactively Asciidoctor's API and object model with syntax highlighting:

    [1] pry(#<Asciidoctor::Section>)> @document

You can also query Asciidoctor's documentation:

    [4] pry(#<Asciidoctor::Section>)> ? find_by

If you install the `pry-byebug` gem you get additional debugging capabilities.
See the gem's documentation for details.

=== References

* https://github.com/asciidoctor/asciidoctor.org/issues/80#issuecomment-145698579
* https://pry.github.io
* http://discuss.asciidoctor.org/Interactively-debugging-a-template-with-a-REPL-td4498.html

== Manual Tests

In order to help troubleshoot issues and test syntax improvements, some minimalist AsciiDoc test files are provided.
You can render the tests files and then load them in a browser and check if `asciidoctor-revealjs` behaves as expected.

=== Initial Setup

Make sure to have a working version of `asciidoctor-reveals` this is usually
done with `bundler`:

 $ bundle config --local github.https true
 $ bundle --path=.bundle/gems --binstubs=.bundle/.bin

Go to `test/doctest` folder and install `reveal.js`:

 $ cd test/doctest/
 $ git clone https://github.com/hakimel/reveal.js.git

=== Render tests into .html

From the project's root directory:

 $ bundle exec rake doctest::generate FORCE=yes

=== Open rendered files

NOTE: Right now, https://github.com/asciidoctor/asciidoctor-doctest/issues/12[doctest issue #12] means that the generated examples will not be pretty.

You can open the generated `.html` in `test/doctest/` in a Web browser.


== Asciidoctor API's gotchas

=== Attribute inheritance

The `attr` and `attr?` methods inherit by default.
That means if they don't find the attribute defined on the Node, they look on the document.

You only want to enable inheritance if you intend to allow an attribute of the same name to be controlled globally.
That might be good for configuring transitions. For instance:

[source,asciidoc]
----
= My Slides
:transition-speed: fast

== First Slide
----

However, there may be attributes that you don't want to inherit.
If that's the case, you generally use the form:

    attr('name', nil, false)

The second parameter value is the default attribute value, which is `nil` by default.

Relevant documentation: {url-asciidoctor-abstractnode-attr}


== Merge / Review policy

Any non-trivial change should be integrated in master via a pull-request.
This gives the community a chance to participate and helps write better code because it encourages people to review their own patches.

Pull requests should come from personal forks in order not the clutter the upstream repository.

=== Wait time

Once a pull request is submitted, let it sit for 24-48 hours for small changes.
If you get positive feedback you can merge before the sitting time frame.
If you don't get feedback, just merge after the sitting time frame.

Larger changes should sit longer at around a week.
Positive feedback or no feedback should be handled like for small changes.

Breaking changes should sit until a prominent contributor comments on the changes.
Ping `@mojavelinux` and `@obilodeau` if necessary.

Remember that this is a slower moving project since people are not designing slides everyday.
Well, for most people.

=== Work-in-progress pull-requests

Letting know to the maintainers that you are working on a feature or a fix is useful.
Early communication often times save time consuming mistakes or avoids duplicated effort.
We encourage contributors to communicate with us early.

Branches on forks of this project are not very visible to maintainers as much as pull requests (PR).
For this reason we recommend to open a draft PR to let everyone know that you are working on a specific topic.
Now, instead of prepending "`WIP`", we recommend using GitHub "`draft pull request`" feature instead.


=== "`needs review`" label

You can apply that label to a pull request that is complete and ready for review.

Makes triaging easier.

== Node package

=== Test locally

The converter is written natively in JavaScript (in `js/src`), so there is no build step.
In order to test the Node package, create a tarball of the project.

 $ npm pack

That last command will produce a file named `asciidoctor-reveal.js-<version>.tgz` in the working directory.

Then, create a test project adjacent to the clone of the [.path]`asciidoctor-reveal.js` repository:

 $ mkdir test-project
 $ cd test-project

Now, install the dependencies from the tarball:

 $ npm i --save ../asciidoctor-reveal.js/asciidoctor-reveal.js-<version>.tgz

NOTE: The relative portion of the last command is where you are installing the local `asciidoctor-reveal.js` version from.

Then proceed as documented in the `README.adoc`.

=== Debugging

To debug the JavaScript application, just add `--node-arg=--inspect-brk` to the npx command to run the application.
For example:

 $ npx --node-arg=--inspect-brk asciidoctor-revealjs -v presentation.adoc

Then open the Chrome Dev Tools and click on the Node logo in the top left corner.


== RubyGem package

[#ruby-localversion]
=== Test a local asciidoctor-revealjs version

The converter is written in plain Ruby (in `lib/asciidoctor_revealjs/converter.rb`), so there is no build step.

In a clean directory besides the `asciidoctor-reveal.js` repository, create the following `Gemfile` file:

[source,ruby]
----
source 'https://rubygems.org'
gem 'asciidoctor-revealjs', :path => '../asciidoctor-reveal.js'
----

Then run:

  $ bundle --path=.bundle/gems --binstubs=.bundle/.bin

== Update dependencies

Update one dependency at a time by bumping its version manually, then install it and run the tests.

NOTE: Avoid `bundle update` and `npm update`: they may upgrade many (transitive) dependencies at once, which makes regressions much harder to track down.

For a Ruby dependency, bump its version in `asciidoctor-revealjs.gemspec` (or in the `Gemfile`), then:

[source,console]
----
bundle install
bundle exec rubocop
bundle exec rake test
bundle exec rake examples:convert
----

For a JavaScript dependency, bump its version in `package.json`, then:

[source,console]
----
npm install
npm test
npm run examples
----

== Release process

=== Prepare the release

. Make sure that the changelog is up-to-date
+
[TIP]
====
You can get the list of all contributors using `git` (don't forget to replace `%prev-version-tag%` with the previous tag name):

 $ git log %prev-version-tag%.. --format="%aN" --reverse | perl -e 'my %dedupe; while (<STDIN>) { print unless $dedupe{$_}++}' | sort
====

. Make sure that the highlight plugin code embed in _lib/asciidoctor_revealjs/highlightjs.rb_ is up-to-date with the version of reveal.js
. Make sure the changelog entry for the version you are about to release is committed and pushed to `master`.

=== Release

The release is fully automated and triggered from GitHub Actions.

Both registries use trusted publishing (OIDC), so no API key or token needs to be configured:
publishing to rubygems.org relies on https://guides.rubygems.org/trusted-publishing/[RubyGems trusted publishing]
and publishing to npmjs.com relies on https://docs.npmjs.com/trusted-publishers[npm trusted publishers].
See the `.github/workflows/release.yml` file for details.

To trigger a release:

. Go to the https://github.com/asciidoctor/asciidoctor-reveal.js/actions/workflows/release.yml[Release workflow] on GitHub Actions.
. Click *Run workflow*, keep the `master` branch selected, and enter the version to release (e.g., `5.3.0` or `5.3.0-beta.1`).
. Click *Run workflow*.

The workflow bumps the version in _package.json_ and _lib/asciidoctor_revealjs/version.rb_ and runs the tests.
Only if the tests pass does it commit, tag (`v%version%`) and push to `master`, then publish to rubygems.org and npmjs.com and build the single executable binaries (one per platform) attached to the GitHub release.

[NOTE]
====
The `master` branch must allow the `github-actions[bot]` to push the release commits and tag.
If branch protection rules reject the push, the release will fail at the *Push release commits and tag* step.
====

Once the https://github.com/asciidoctor/asciidoctor-reveal.js/actions?query=workflow%3Arelease[release workflow]
has been completed:

[%interactive]
* [ ] Check that the new version is available on https://rubygems.org/gems/asciidoctor-revealjs[rubygems.org]
* [ ] Check that the new version is available on https://www.npmjs.com/package/@asciidoctor/reveal.js[npmjs.com]
* [ ] Check that a https://github.com/asciidoctor/asciidoctor-reveal.js/releases[release has been created on GitHub].

In addition, you can submit pull requests to downstream project:

[%interactive]
* [ ] submit a pull request downstream to update Asciidoctor reveal.js version in the Asciidoctor Docker Container
** modify the `Dockerfile`, `tests/asciidoctor.bats`, `README.md` and `README.adoc` in: https://github.com/asciidoctor/docker-asciidoctor
* [ ] submit a pull request downstream to update AsciidoctorJ reveal.js version
** modify `gradle.properties` and `asciidoctorj-revealjs/gradle.properties`. if `reveal.js`version has been updated, +
also amend `WhenBackendIsRevealJs.java` in both `tests` and `itests` folders and `README.adoc` in: https://github.com/asciidoctor/asciidoctorj-reveal.js

=== Prepare next version

This step is optional and should only be done after a *final* release (not after a pre-release such as `5.3.0-beta.1`).

Trigger the https://github.com/asciidoctor/asciidoctor-reveal.js/actions/workflows/post-release.yml[Begin next development version workflow] from GitHub Actions.
It bumps the minor version to the next `-dev` version (e.g., `5.3.0` -> `5.4.0-dev`) in _package.json_, _lib/asciidoctor_revealjs/version.rb_ and _docs/antora.yml_, then commits and pushes to `master`.

Alternatively, you can run it locally and follow the printed instructions:

 $ npm run release:next

=== Maintenance branch

You can (not must) create a maintenance branch from a tag.
Please use the following name convention: `\{major}.\{minor}.x` (e.g., `4.1.x`).

[%interactive]
* [ ] push the maintenance branch: `git push origin 4.1.x`
* [ ] don't forget to update Antora playbook to add this branch: https://github.com/asciidoctor/docs.asciidoctor.org/edit/main/antora-playbook.yml

=== New major version

In case of a new major version, you must follow the steps described for a <<_maintenance_branch,Maintenance branch>>.


== Ruby and asciidoctor-doctest tests

=== Running tests

We recommend tests to be run with a fresh installation of all dependencies in a local folder that won't affect your Ruby install (a `.bundle/` in this directory):

 $ bundle --path=.bundle/gems --binstubs=.bundle/.bin

Then you can execute the tests with:

 $ bundle exec rake doctest

However, if you have all dependencies properly installed this command should run the tests successfully:

 $ rake doctest

=== Generating HTML test target

Tests were bootstrapped by https://github.com/asciidoctor/asciidoctor-doctest/#generate-examples[generating them from asciidoctor-doctest's test corpus^] and current asciidoctor-revealjs' slim template engine.
This is done using the following command:

 $ bundle exec rake doctest:generate FORCE=y

=== Custom tests

Files in the `examples/` directory are used as tests.
Resulting slides are kept in `test/doctest/`.


== Netlify Integration

On every commit or PR, the {url-netlify}[Netlify^] service will convert some examples into slides and host the resulting pages on its platform where it will be visible by anyone.
It hosts the converted HTML files, reveal.js framework and static content like images and CSS.
This integration will allow us to preview PRs and demo features to users (source and converted result).
See the `publish` rake task in `Rakefile` and the `netlify.toml` configuration file.

=== Sensitive Data Accidentally Pushed Out

Only content that is copied into the `public/` directory will be published on the Netlify site.
If, by accident, something sensitive is copied over there, delete it, rewrite the git history to remove the sensitive information and force push the branch.
Reach out to our Netlify integration contact to make sure that deployed branches were rebuilt and no longer contain the sensitive information.

=== Integration Contact

Main Contact: {url-gh-ggrosetie}[@ggrossetie^]

Also, in order to stay with a free plan, only the following people have control over our Netlify integration:
{url-gh-ggrossetie}[@ggrossetie^],
{url-gh-mojavelinux}[@mojavelinux^] and
{url-gh-graphitefriction}[@graphitefriction^].
