= Compatibility Matrix

[[revealjs-compatibility-matrix]]
== reveal.js compatibility matrix

We try as much as possible to be compatible with a broad range of reveal.js versions.
However, changes made by that project sometimes forces us to drop compatibility with older reveal.js releases.
This table tracks this compatibility.

|===
|Asciidoctor reveal.js version |reveal.js version

|4.x
|3.9 - 3.8

|3.x, 2.x, 1.x
|3.7 - 3.0

|Unversioned releases
|2.x
|===


[[asciidoctorjs-compatibility-matrix]]
== Asciidoctor.js compatibility matrix

NOTE: This section is intended only for more advanced users who combine extensions or maintain slide decks over many releases and need to update their dependencies.

Due to our Ruby to JavaScript conversion process, published npm packages have strict requirements with which version of Asciidoctor.js they are compatible with.
This table tracks this compatibility.

|===
|Asciidoctor reveal.js version |Asciidoctor.js version

|3.x
|2.x

|2.x
|1.5.9

|1.1.x
|1.5.6-preview.4
|===

Be aware that it is always possible to recompile the converter into JavaScript from source so compatibility can be created by anyone if needed.
More details on that topic can be found xref:project:hacking.adoc#node-binary-compatibility[in the development guide].

