# frozen_string_literal: true

# The CSS generated by the Asciidoctor reveal.js converter to further integrate
# AsciiDoc's existing semantic with reveal.js. It is embedded verbatim into the
# document <head> by the converter.

module Asciidoctor
  module Revealjs
    module Stylesheet
      COMPATIBILITY = File.read(File.join(__dir__, 'data', 'compatibility.css')).freeze
    end
  end
end
