#!/usr/bin/env node

'use strict'

process.title = 'asciidoctor-revealjs'

const { Options, Invoker } = require('@asciidoctor/cli')
const asciidoctorRevealjs = require('@asciidoctor/reveal.js')
asciidoctorRevealjs.register()

const options = new Options({backend: 'revealjs'}).parse(process.argv)
new Invoker(options).invoke()
