#!/usr/bin/env node

'use strict'

process.title = 'asciidoctor-revealjs'

const { Options, Invoker } = require('@asciidoctor/cli')
const asciidoctorRevealjs = require('@asciidoctor/reveal.js')
asciidoctorRevealjs.register()

const options = new Options({backend: 'revealjs'}).parse(process.argv)

class RevealJsInvoker extends Invoker {
  printVersion () {
    const pkg = require('../package.json')
    process.stdout.write(`Asciidoctor-Reveal.js ${pkg.version} using `)
    super.printVersion()
  }
}

new RevealJsInvoker(options).invoke()
